### ISSUE TITLE
Too much logging 

### ISSUE THREAD

**Issue by YojanaGadiya** [durrantlab/binana#3]
Dear Binana team,

It is great that you have the logging enabled for the command line, allowing users to know what is happening, but there are times when the logs get accumulated too much to have any meaning in the terminal. Is there a possible to either move these logs to a file or disable logs from the command line at times?

Thank You.

Regards,
Yojana Gadiya

**Comment by jacobdurrant** [comment]
Hi Yojana. Thanks so much for your interest in BINANA. One way to save the logs to a file, assuming you're using the UNIX command line, is to redirect them using the ">" symbol. For example, you could use something like this to redirect all of the output to the log.out file:

python script.py > log.out

I hope this helps, and thanks again for your interest in BINANA!

**Comment by YojanaGadiya** [comment]
Thank you @jacobdurrant for your prompt reply.
